"""guardar value de enums en vez de name

Revision ID: 11a47b7e32d6
Revises: 9793bb205337
Create Date: 2026-08-14 16:52:08.305213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a47b7e32d6'
down_revision: Union[str, None] = '9793bb205337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archivos_procesados', 'tipo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ReportePlantaProduccion', 'Trazabilidad', name='tipoarchivo', native_enum=False),
               existing_nullable=False)
    op.alter_column('lineas', 'tipo_linea',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Materia Prima (DI)', 'Materia Prima (Producción Propia)', 'Producto', 'Desecho', name='tipolinea', native_enum=False),
               existing_nullable=False)
    op.alter_column('lineas', 'estado',
               existing_type=sa.VARCHAR(length=22),
               type_=sa.Enum('OK - un solo DI', 'OK - mismo barco, DI parcial+definitivo', 'REVISAR - DI de barcos distintos', 'N/A - línea de consumo', 'N/A - lote no determinado', 'N/A - lote no resuelto en este archivo', 'N/A', name='estadolote', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lineas', 'estado',
               existing_type=sa.Enum('OK - un solo DI', 'OK - mismo barco, DI parcial+definitivo', 'REVISAR - DI de barcos distintos', 'N/A - línea de consumo', 'N/A - lote no determinado', 'N/A - lote no resuelto en este archivo', 'N/A', name='estadolote', native_enum=False),
               type_=sa.VARCHAR(length=22),
               existing_nullable=False)
    op.alter_column('lineas', 'tipo_linea',
               existing_type=sa.Enum('Materia Prima (DI)', 'Materia Prima (Producción Propia)', 'Producto', 'Desecho', name='tipolinea', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('archivos_procesados', 'tipo',
               existing_type=sa.Enum('ReportePlantaProduccion', 'Trazabilidad', name='tipoarchivo', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
