"""esquema inicial

Revision ID: 5a185d8019fb
Revises: 
Create Date: 2026-08-13 16:29:35.081576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a185d8019fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('tipo_linea', sa.Enum('MATERIA_PRIMA_DI', 'MATERIA_PRIMA_PROPIA', 'PRODUCTO', 'DESECHO', name='tipolinea', native_enum=False), nullable=False),
    sa.Column('estado', sa.Enum('OK_UN_DI', 'OK_PARCIAL_DEFINITIVO', 'REVISAR', 'NA_LINEA_CONSUMO', 'NA_LOTE_NO_DETERMINADO', 'NA_LOTE_NO_RESUELTO', 'NA', name='estadolote', native_enum=False), nullable=False),
    sa.Column('n_declaracion', sa.String(length=50), nullable=False),
    sa.Column('di', sa.String(length=50), nullable=False),
    sa.Column('declaracion_origen', sa.String(length=50), nullable=False),
    sa.Column('agente', sa.String(length=100), nullable=False),
    sa.Column('fecha_desembarque_di', sa.Date(), nullable=True),
    sa.Column('fecha_elaboracion_linea', sa.Date(), nullable=True),
    sa.Column('fecha_declaracion', sa.Date(), nullable=True),
    sa.Column('producto', sa.Text(), nullable=False),
    sa.Column('especie', sa.String(length=200), nullable=False),
    sa.Column('proceso_producto', sa.String(length=200), nullable=False),
    sa.Column('tipo_frio', sa.String(length=200), nullable=False),
    sa.Column('producto_global', sa.String(length=200), nullable=False),
    sa.Column('preparacion', sa.String(length=300), nullable=False),
    sa.Column('codigo_producto', sa.String(length=50), nullable=False),
    sa.Column('nombre_bodega', sa.String(length=200), nullable=False),
    sa.Column('toneladas', sa.Float(), nullable=False),
    sa.Column('fila_original', sa.Integer(), nullable=False),
    sa.Column('archivo_origen', sa.String(length=500), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('n_declaracion', 'lote', 'tipo_linea', 'codigo_producto', 'fila_original', name='uq_linea_dedup_key')
    )
    op.create_index(op.f('ix_lineas_di'), 'lineas', ['di'], unique=False)
    op.create_index(op.f('ix_lineas_especie'), 'lineas', ['especie'], unique=False)
    op.create_index(op.f('ix_lineas_fecha_declaracion'), 'lineas', ['fecha_declaracion'], unique=False)
    op.create_index(op.f('ix_lineas_lote'), 'lineas', ['lote'], unique=False)
    op.create_index(op.f('ix_lineas_n_declaracion'), 'lineas', ['n_declaracion'], unique=False)
    op.create_table('materia_prima_externa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lote_interno', sa.String(length=100), nullable=False),
    sa.Column('di_externo', sa.String(length=100), nullable=False),
    sa.Column('barco', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=200), nullable=False),
    sa.Column('fecha_recalada', sa.Date(), nullable=True),
    sa.Column('archivo_origen', sa.String(length=500), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_interno', 'di_externo', 'especie', name='uq_mp_externa_dedup_key')
    )
    op.create_index(op.f('ix_materia_prima_externa_di_externo'), 'materia_prima_externa', ['di_externo'], unique=False)
    op.create_index(op.f('ix_materia_prima_externa_lote_interno'), 'materia_prima_externa', ['lote_interno'], unique=False)
    op.create_table('productividad_diaria',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('n_declaraciones', sa.Integer(), nullable=False),
    sa.Column('n_lineas_totales', sa.Integer(), nullable=False),
    sa.Column('n_lineas_materia_prima', sa.Integer(), nullable=False),
    sa.Column('n_lineas_produccion', sa.Integer(), nullable=False),
    sa.Column('n_di_distintos', sa.Integer(), nullable=False),
    sa.Column('n_especies_distintas', sa.Integer(), nullable=False),
    sa.Column('toneladas_producto', sa.Float(), nullable=False),
    sa.Column('toneladas_materia_prima', sa.Float(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('fecha')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('OPERADOR', 'ADMIN', name='rol', native_enum=False), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('archivos_procesados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=500), nullable=False),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.Enum('PRODUCCION', 'TRAZABILIDAD_INTERNA', name='tipoarchivo', native_enum=False), nullable=False),
    sa.Column('procesado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('procesado_por_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['procesado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_archivo', 'hash_contenido', name='uq_archivo_hash')
    )
    op.create_table('casos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('fecha_detectado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('di_asociados', sa.String(length=300), nullable=False),
    sa.Column('agentes', sa.String(length=300), nullable=False),
    sa.Column('n_declaraciones', sa.Integer(), nullable=False),
    sa.Column('estado_revision', sa.Enum('PENDIENTE', 'CONFIRMADO_ERROR', 'FALSO_POSITIVO', name='estadorevision', native_enum=False), nullable=False),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_por_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casos_lote'), 'casos', ['lote'], unique=True)
    op.create_table('ejecuciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archivo_id', sa.UUID(), nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archivo_nombre', sa.String(length=500), nullable=False),
    sa.Column('lotes_ok', sa.Integer(), nullable=False),
    sa.Column('lotes_ok_parcial', sa.Integer(), nullable=False),
    sa.Column('lotes_revisar', sa.Integer(), nullable=False),
    sa.Column('lotes_sin_determinar', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['archivo_id'], ['archivos_procesados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sin_determinar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ejecucion_id', sa.UUID(), nullable=False),
    sa.Column('n_declaracion', sa.String(length=50), nullable=False),
    sa.Column('especie', sa.String(length=200), nullable=False),
    sa.Column('fecha_declaracion', sa.Date(), nullable=True),
    sa.Column('di_toneladas', sa.Text(), nullable=False),
    sa.Column('out_toneladas', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sin_determinar')
    op.drop_table('ejecuciones')
    op.drop_index(op.f('ix_casos_lote'), table_name='casos')
    op.drop_table('casos')
    op.drop_table('archivos_procesados')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('productividad_diaria')
    op.drop_index(op.f('ix_materia_prima_externa_lote_interno'), table_name='materia_prima_externa')
    op.drop_index(op.f('ix_materia_prima_externa_di_externo'), table_name='materia_prima_externa')
    op.drop_table('materia_prima_externa')
    op.drop_index(op.f('ix_lineas_n_declaracion'), table_name='lineas')
    op.drop_index(op.f('ix_lineas_lote'), table_name='lineas')
    op.drop_index(op.f('ix_lineas_fecha_declaracion'), table_name='lineas')
    op.drop_index(op.f('ix_lineas_especie'), table_name='lineas')
    op.drop_index(op.f('ix_lineas_di'), table_name='lineas')
    op.drop_table('lineas')
    # ### end Alembic commands ###
