"""dedup lineas_crudas por declaracion no por archivo

Revision ID: 8cb3bb3f86a6
Revises: 11a47b7e32d6
Create Date: 2026-08-16 19:35:52.777107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb3bb3f86a6'
down_revision: Union[str, None] = '11a47b7e32d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_linea_cruda_archivo_fila', 'lineas_crudas', type_='unique')
    op.create_unique_constraint('uq_linea_cruda_declaracion_fila', 'lineas_crudas', ['n_declaracion', 'fila_original'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_linea_cruda_declaracion_fila', 'lineas_crudas', type_='unique')
    op.create_unique_constraint('uq_linea_cruda_archivo_fila', 'lineas_crudas', ['archivo_id', 'fila_original'])
    # ### end Alembic commands ###
