"""agregar lineas_crudas para facsimil

Revision ID: 9793bb205337
Revises: e27193aa2df9
Create Date: 2026-08-14 14:56:29.875818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9793bb205337'
down_revision: Union[str, None] = 'e27193aa2df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineas_crudas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archivo_id', sa.UUID(), nullable=False),
    sa.Column('fila_original', sa.Integer(), nullable=False),
    sa.Column('n_declaracion', sa.String(length=50), nullable=False),
    sa.Column('fecha_declaracion', sa.Date(), nullable=True),
    sa.Column('matprod', sa.String(length=20), nullable=False),
    sa.Column('tipo_item', sa.String(length=20), nullable=False),
    sa.Column('codigo_producto', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('especie', sa.String(length=200), nullable=False),
    sa.Column('toneladas', sa.Float(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('tipo_origen', sa.String(length=20), nullable=False),
    sa.Column('fecha_elaboracion', sa.Date(), nullable=True),
    sa.Column('agente', sa.String(length=100), nullable=False),
    sa.Column('declaracion_origen', sa.String(length=50), nullable=False),
    sa.Column('nombre_bodega', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['archivo_id'], ['archivos_procesados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archivo_id', 'fila_original', name='uq_linea_cruda_archivo_fila')
    )
    op.create_index(op.f('ix_lineas_crudas_archivo_id'), 'lineas_crudas', ['archivo_id'], unique=False)
    op.create_index(op.f('ix_lineas_crudas_n_declaracion'), 'lineas_crudas', ['n_declaracion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineas_crudas_n_declaracion'), table_name='lineas_crudas')
    op.drop_index(op.f('ix_lineas_crudas_archivo_id'), table_name='lineas_crudas')
    op.drop_table('lineas_crudas')
    # ### end Alembic commands ###
