"""auth por contrasena en vez de oauth

Revision ID: e27193aa2df9
Revises: 5a185d8019fb
Create Date: 2026-08-14 13:20:34.417367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27193aa2df9'
down_revision: Union[str, None] = '5a185d8019fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_constraint('usuarios_google_sub_key', 'usuarios', type_='unique')
    op.drop_column('usuarios', 'google_sub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('google_sub', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('usuarios_google_sub_key', 'usuarios', ['google_sub'])
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###
